name: "RecruitmentInformation"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  GetRecruitmentInformation:
    runs-on: ubuntu-latest
    steps:
      - name: "Set python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade requests

      - name: "Get recruitmentInformation and send mail ..."
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECEIVER: ${{ secrets.RECEIVER }}
        run: |
          wget -O "RecruitmentInformation.zip" '${{ secrets.DOWNLOADURL }}'
          unzip -o "RecruitmentInformation.zip" -d "$(pwd)/"
          python RecruitmentInformation.py